# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'runes_help.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainHelp(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(389, 302)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setObjectName("btn")
        self.gridLayout.addWidget(self.btn, 1, 0, 1, 1)
        self.cmb = QtWidgets.QComboBox(self.centralwidget)
        self.cmb.setObjectName("cmb")
        self.gridLayout.addWidget(self.cmb, 0, 0, 1, 1)
        self.lbl2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl2.setObjectName("lbl2")
        self.gridLayout.addWidget(self.lbl2, 3, 0, 1, 1)
        self.txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt.setEnabled(True)
        self.txt.setObjectName("txt")
        self.gridLayout.addWidget(self.txt, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 389, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "все значения"))
        self.btn.setText(_translate("MainWindow", "узнать значение"))
        self.lbl2.setText(_translate("MainWindow", " "))
