# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'runes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(353, 290)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnr = QtWidgets.QPushButton(self.centralwidget)
        self.btnr.setObjectName("btnr")
        self.gridLayout.addWidget(self.btnr, 6, 0, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 1, 0, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 4, 0, 1, 1)
        self.btn5_new = QtWidgets.QPushButton(self.centralwidget)
        self.btn5_new.setObjectName("btn5_new")
        self.gridLayout.addWidget(self.btn5_new, 5, 0, 1, 1)
        self.btn_help = QtWidgets.QPushButton(self.centralwidget)
        self.btn_help.setObjectName("btn_help")
        self.gridLayout.addWidget(self.btn_help, 7, 0, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.history = QtWidgets.QPushButton(self.centralwidget)
        self.history.setObjectName("history")
        self.gridLayout.addWidget(self.history, 8, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "гадание"))
        self.btnr.setText(_translate("MainWindow", "расклад на произвольное количество рун"))
        self.btn1.setText(_translate("MainWindow", "расклад \"руна Одина\" (одна руна)"))
        self.btn5.setText(_translate("MainWindow", "расклад на пять рун"))
        self.btn5_new.setText(_translate("MainWindow", "расклад \"стороны света\" (пять рун)"))
        self.btn_help.setText(_translate("MainWindow", "посмотреть значения рун"))
        self.btn3.setText(_translate("MainWindow", "расклад \"три сестры\" (три руны)"))
        self.label.setText(_translate("MainWindow", "выберите, что вам нужно"))
        self.history.setText(_translate("MainWindow", "посмотреть историю"))
